### ISSUE TITLE
Fatal error in 2.1.1 startup on ubuntu 16.04

### ISSUE THREAD

**Issue by whyscream** [milter-manager/milter-manager#128]
After upgrading to 2.1.1 on ubuntu xenial, I receive the following error:
```
Jun 30 13:17:08 alison milter-manager[32313]: TypeError: no implicit conversion of nil into String:
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/rspamd-proxy-detector.rb:10:in `executable?'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/rspamd-proxy-detector.rb:10:in `detect'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/detector.rb:93:in `detect_rspamd_proxy_connection_spec'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/systemd-detector.rb:110:in `guess_application_specific_spec'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/systemd-detector.rb:96:in `guess_spec'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/systemd-detector.rb:24:in `enabled?'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/debian-detector.rb:15:in `apply'
Jun 30 13:17:08 alison milter-manager[32313]: /etc/milter-manager/defaults/debian.conf:57:in `block in load_configuration'
Jun 30 13:17:08 alison milter-manager[32313]: /etc/milter-manager/defaults/debian.conf:54:in `each'
Jun 30 13:17:08 alison milter-manager[32313]: /etc/milter-manager/defaults/debian.conf:54:in `load_configuration'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:415:in `block in load'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:414:in `each'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:414:in `load'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:420:in `load_if_exist'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:432:in `load_default'
Jun 30 13:17:08 alison milter-manager[32313]: /etc/milter-manager/milter-manager.conf:4:in `load_configuration'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:344:in `block in load'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/core/callback.rb:20:in `guard'
Jun 30 13:17:08 alison milter-manager[32313]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:343:in `load'
```

I can make the error 'go away' by commenting  the `load_default` directive from milter-manager.conf, but then at runtime various errors (f.i. `[egg][error] must set connection spec: spamass-milter`) happen because not all services are completely configured.

Installed versions:
```
ii  libmilter-client0        2.1.1-2~xenial1              amd64        Libraries and tools for implementing milter protocol (client-side)
ii  libmilter-core0          2.1.1-2~xenial1              amd64        Common library for implementing milter protocol
ii  libmilter-dev            8.15.2-3                     amd64        Sendmail Mail Filter API (Milter) (development files)
ii  libmilter-manager0       2.1.1-2~xenial1              amd64        Libraries for extending milter manager by C
ii  libmilter-server0        2.1.1-2~xenial1              amd64        Libraries and tools for implementing milter protocol (server-side)
ii  libmilter1.0.1:amd64     8.15.2-3                     amd64        Sendmail Mail Filter API (Milter)
ii  milter-manager           2.1.1-2~xenial1              amd64        Milter to use milters effectively
ii  ruby-milter-client       2.1.1-2~xenial1              amd64        Ruby bindings for milter client (Ruby interface)
ii  ruby-milter-core         2.1.1-2~xenial1              amd64        Ruby bindings for milter core library (Ruby interface)
ii  ruby-milter-server       2.1.1-2~xenial1              amd64        Ruby bindings for milter server (Ruby interface)
ii  spamass-milter           0.3.2-1                      amd64        milter for filtering mail through spamassassin
```

**Comment by whyscream** [comment]
Note: I don't have rspamd installed.

I fixed the issue locally by commenting line 93 in `/usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/detector.rb`:
```
    def detect_rspamd_proxy_connection_spec
#      Milter::Manager::RspamdProxyDetector.new(rspamadm_command).detect
    end
```

**Comment by okkez** [comment]
Thank you for reporting.
You can do same thing as following (/etc/milter-manager/defaults/debian.conf):

```diff
diff --git a/data/defaults/debian.conf b/data/defaults/debian.conf
index dfa417d8..638f3591 100644
--- a/data/defaults/debian.conf
+++ b/data/defaults/debian.conf
@@ -42,14 +42,14 @@ candidates = [
       "No Stress",
     ],
   ],
-  [
-    "rspamd",
-    [
-      "Remote Network",
-      "Unauthenticated",
-      "No Stress",
-    ],
-  ]
+  # [
+  #   "rspamd",
+  #   [
+  #     "Remote Network",
+  #     "Unauthenticated",
+  #     "No Stress",
+  #   ],
+  # ]
 ]
 candidates.each do |candidate, conditions|
   detector = DebianDetector.new(configuration, candidate)
```

I will fix this issue in next release.

**Comment by whyscream** [comment]
Just checked your solution, it does work.
I reinstalled `libmilter-manager0` to overwrite all code I messed with, and things continue to work as expected now.

**Comment by okkez** [comment]
Thank you for confirmation.

**Comment by okkez** [comment]
Relased 2.1.2
