### ISSUE TITLE
Error Run Milter On Cento7.Rhel

### ISSUE THREAD

**Issue by ri7nz** [milter-manager/milter-manager#130]
i have error when i running milter-manager on shell command

```shell
[2017-10-14T15:05:15.813922Z]: TypeError: no implicit conversion of nil into String:
[2017-10-14T15:05:15.814086Z]: /usr/lib64/milter-manager/binding/lib/milter/manager/rspamd-proxy-detector.rb:10:in `executable?'
[2017-10-14T15:05:15.814135Z]: /usr/lib64/milter-manager/binding/lib/milter/manager/rspamd-proxy-detector.rb:10:in `detect'
[2017-10-14T15:05:15.814178Z]: /usr/lib64/milter-manager/binding/lib/milter/manager/detector.rb:93:in `detect_rspamd_proxy_connection_spec'
[2017-10-14T15:05:15.814221Z]: /usr/lib64/milter-manager/binding/lib/milter/manager/systemd-detector.rb:110:in `guess_application_specific_spec'
[2017-10-14T15:05:15.814261Z]: /usr/lib64/milter-manager/binding/lib/milter/manager/systemd-detector.rb:96:in `guess_spec'
[2017-10-14T15:05:15.814302Z]: /usr/lib64/milter-manager/binding/lib/milter/manager/systemd-detector.rb:24:in `enabled?'
[2017-10-14T15:05:15.814341Z]: /usr/lib64/milter-manager/binding/lib/milter/manager/redhat-detector.rb:31:in `apply'
[2017-10-14T15:05:15.814380Z]: /etc/milter-manager/defaults/redhat.conf:56:in `block in load_configuration'
[2017-10-14T15:05:15.814422Z]: /etc/milter-manager/defaults/redhat.conf:53:in `each'
[2017-10-14T15:05:15.814477Z]: /etc/milter-manager/defaults/redhat.conf:53:in `load_configuration'
[2017-10-14T15:05:15.814513Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
[2017-10-14T15:05:15.814559Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
[2017-10-14T15:05:15.814609Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:415:in `block in load'
[2017-10-14T15:05:15.814643Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:414:in `each'
[2017-10-14T15:05:15.814688Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:414:in `load'
[2017-10-14T15:05:15.814724Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:420:in `load_if_exist'
[2017-10-14T15:05:15.814768Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:435:in `load_default'
[2017-10-14T15:05:15.814814Z]: /etc/milter-manager/milter-manager.conf:4:in `load_configuration'
[2017-10-14T15:05:15.814861Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
[2017-10-14T15:05:15.814909Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
[2017-10-14T15:05:15.814958Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:344:in `block in load'
[2017-10-14T15:05:15.815002Z]: /usr/lib64/milter-manager/binding/lib/milter/core/callback.rb:20:in `guard'
[2017-10-14T15:05:15.815050Z]: /usr/lib64/milter-manager/binding/lib/milter/manager.rb:343:in `load'
```
Other Information : 
- Postfix 2.10.1
- Centos7
- ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

**Comment by kou** [comment]
Thanks for your report.
It's the same problem as #128. We already have fix in master. We should release a new version that includes the fix soon.

You can avoid the error by changing `/etc/milter-manager/defaults/redhat.conf` like the following:

```diff
--- /etc/milter-manager/defaults/redhat.conf.orig	2017-06-28 15:55:45.000000000 +0900
+++ /etc/milter-manager/defaults/redhat.conf	2017-10-15 11:55:16.301140749 +0900
@@ -41,14 +41,14 @@
       "No Stress",
     ],
   ],
-  [
-    "rspamd",
-    [
-      "Remote Network",
-      "Unauthenticated",
-      "No Stress",
-    ],
-  ],
+#  [
+#    "rspamd",
+#    [
+#      "Remote Network",
+#      "Unauthenticated",
+#      "No Stress",
+#    ],
+#  ],
 ]
 candidates.each do |candidate, conditions, spec_detector|
   detector = RedHatDetector.new(configuration, candidate, &spec_detector)
```

**Comment by ri7nz** [comment]
okay thank you very much

**Comment by okkez** [comment]
Relased 2.1.2
