### ISSUE TITLE
Unable to run on FreeBSD

### ISSUE THREAD

**Issue by hkuwabara3** [milter-manager/milter-manager#154]
FrerBSD 13.0-RELEASE-p3 に導入しましたが、全く動作しません。
pkg でも ports でも起動できない。

```
# /usr/local/sbin/milter-manager
[2022-01-17T01:35:16.859076Z]: unknown error is occurred: <NULL pointer given (ArgumentError)
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/milter-manager/binding/lib/milter/core.rb:18:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/milter-manager/binding/lib/milter/client.rb:16:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/milter-manager/binding/lib/milter.rb:16:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/milter-manager/binding/lib/milter/manager.rb:25:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
>
Segmentation fault (core dumped)
```

何がいけないのか全く分からない。

**Comment by kou** [comment]
自分でビルドしたmilter-managerでは再現しないのでportsでのビルド方法が関係あると思います。
portsのビルドログを見せてもらえますか？

**Comment by kou** [comment]
あれ、portsのmilter-managerパッケージのバージョンっていくつですか？

**Comment by hkuwabara3** [comment]
PORTVERSION=    2.1.1 
です。
一旦、port は消して　　pkg で入れ直しましたが、張ったメッセージがでて core dumpします。
Freebsd は素の状態でpkg入れてます。

ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [amd64-freebsd13]
の関係でしょうか？　　

/usr/local/sbin/milter-manager --version　を実行しても同じメッセージです。

rubyはわからないのですが、
/usr/local/lib/milter-manager/binding/lib/milter/manager.rb　の  
require 'milter' を　require './milter' とすると、

/usr/local/lib/milter-manager/module/configuration/milter-manager-ruby-configuration.so: Undefined symbol "rbg_rval2cstr"　となります。

関連する milterは正常に起動できますが、 milter-managerのみ core dumpします。

**Comment by kou** [comment]
portsにパッチを送って最新の2.1.6を使うようにしてみてもらえますか？
FreeBSDで起動時にクラッシュする問題が直っているんです。

**Comment by hkuwabara3** [comment]
あ、そういう問題があるのですね。暫く離れていたので疎くなっています。
ヒントをありがとうございます。

milter-manager-2.1.6.tar.gz は何処にありますでしょうか？

**Comment by kou** [comment]
今はGitHub Releaseに置いています！
https://github.com/milter-manager/milter-manager/releases/tag/2.1.6
https://github.com/milter-manager/milter-manager/releases/download/2.1.6/milter-manager-2.1.6.tar.gz

**Comment by hkuwabara3** [comment]
ビルドしてみましたが、手に負えないので portsができるのを待ちます。
pkg install rubygem-gobject-introspection だけ追加しました。

```
# /usr/local/etc/rc.d/milter-manager start
Starting miltermanager.
[2022-01-17T06:50:55.871110Z]: [configuration][clear][custom]
[2022-01-17T06:50:55.871364Z]: [configuration][path][found] </usr/local/etc/milter-manager/milter-manager.conf>
[2022-01-17T06:50:55.871727Z]: [configuration][load][start] </usr/local/etc/milter-manager/milter-manager.conf>
[2022-01-17T06:50:55.872116Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.888477Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.888640Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.889031Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.889155Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.889502Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.889622Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.890315Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.890425Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.897420Z]: [netstat][detect] <env LANG=C netstat -n -W 2>&1>
[2022-01-17T06:50:55.897683Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.897820Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.898671Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.898796Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.899607Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.899728Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.900221Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.900347Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.901463Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.901587Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.902013Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.902130Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.902473Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.902581Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.903292Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.903404Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.903968Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.904081Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.904643Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.904753Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.905451Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.905566Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.906055Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.906271Z]: [configuration][load][start] </usr/local/etc/milter-manager/defaults/freebsd.conf>
[2022-01-17T06:50:55.925946Z]: [egg][error][set-spec] <milter-opendkim>: invalid connection spec: milter-connection-error-quark:0: port number has invalid character: <inet:port@localhost>: <p>
[2022-01-17T06:50:55.926161Z]: [configuration][load][end] </usr/local/etc/milter-manager/defaults/freebsd.conf>
[2022-01-17T06:50:55.926241Z]: [configuration][load][end] </usr/local/etc/milter-manager/milter-manager.conf>
[2022-01-17T06:50:55.926372Z]: GLib::Error: <milter-opendkim>: invalid connection spec: milter-connection-error-quark:0: port number has invalid character: <inet:port@localhost>: <p>:
[2022-01-17T06:50:55.926411Z]: (eval):1:in `set_connection_spec'
[2022-01-17T06:50:55.926440Z]: (eval):1:in `connection_spec='
[2022-01-17T06:50:55.926468Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:1189:in `method_missing'
[2022-01-17T06:50:55.926531Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager/detector.rb:44:in `block in apply'
[2022-01-17T06:50:55.926578Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:442:in `define_milter'
[2022-01-17T06:50:55.926622Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager/detector.rb:36:in `apply'
[2022-01-17T06:50:55.926669Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager/freebsd-rc-detector.rb:145:in `apply'
[2022-01-17T06:50:55.926716Z]: /usr/local/etc/milter-manager/defaults/freebsd.conf:57:in `block in load_configuration'
[2022-01-17T06:50:55.926760Z]: /usr/local/etc/milter-manager/defaults/freebsd.conf:54:in `each'
[2022-01-17T06:50:55.926802Z]: /usr/local/etc/milter-manager/defaults/freebsd.conf:54:in `load_configuration'
[2022-01-17T06:50:55.926847Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
[2022-01-17T06:50:55.926894Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
[2022-01-17T06:50:55.926939Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:415:in `block in load'
[2022-01-17T06:50:55.926983Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:414:in `each'
[2022-01-17T06:50:55.927027Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:414:in `load'
[2022-01-17T06:50:55.927069Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:420:in `load_if_exist'
[2022-01-17T06:50:55.927112Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:432:in `load_default'
[2022-01-17T06:50:55.927159Z]: /usr/local/etc/milter-manager/milter-manager.conf:4:in `load_configuration'
[2022-01-17T06:50:55.927205Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
[2022-01-17T06:50:55.927247Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
[2022-01-17T06:50:55.927294Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:344:in `block in load'
[2022-01-17T06:50:55.927337Z]: /usr/local/lib/milter-manager/binding/lib/milter/core/callback.rb:20:in `guard'
[2022-01-17T06:50:55.927380Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:343:in `load'
[2022-01-17T06:50:55.937625Z]: [configuration][path][nonexistent] path milter-manager.custom.conf doesn't exist in load path (["/usr/local/etc/milter-manager", "/usr/local/etc/milter-manager"])
[2022-01-17T06:50:55.938280Z]: [configuration][clear][custom]
[2022-01-17T06:50:55.938356Z]: [configuration][path][found] </usr/local/etc/milter-manager/milter-manager.conf>
[2022-01-17T06:50:55.938599Z]: [configuration][load][start] </usr/local/etc/milter-manager/milter-manager.conf>
[2022-01-17T06:50:55.938992Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.940073Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.940187Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.940567Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.940682Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.941047Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.941157Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.941829Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.941953Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.948351Z]: [netstat][detect] <env LANG=C netstat -n -W 2>&1>
[2022-01-17T06:50:55.948616Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.948762Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.949587Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.949708Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.950574Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.950703Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.951231Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.951362Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.952448Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/dnsbl.conf>
[2022-01-17T06:50:55.952575Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.953002Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/remote-network.conf>
[2022-01-17T06:50:55.953124Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.953498Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/restrict-accounts.conf>
[2022-01-17T06:50:55.953621Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.954357Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/s25r.conf>
[2022-01-17T06:50:55.954478Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.955029Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/sendmail-compatible.conf>
[2022-01-17T06:50:55.955152Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.955740Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/stress.conf>
[2022-01-17T06:50:55.955861Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.956569Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/trust.conf>
[2022-01-17T06:50:55.956694Z]: [configuration][load][start] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.957157Z]: [configuration][load][end] </usr/local/etc/milter-manager/applicable-conditions/authentication.conf>
[2022-01-17T06:50:55.957358Z]: [configuration][load][start] </usr/local/etc/milter-manager/defaults/freebsd.conf>
[2022-01-17T06:50:55.974238Z]: [egg][error][set-spec] <milter-opendkim>: invalid connection spec: milter-connection-error-quark:0: port number has invalid character: <inet:port@localhost>: <p>
[2022-01-17T06:50:55.974420Z]: [configuration][load][end] </usr/local/etc/milter-manager/defaults/freebsd.conf>
[2022-01-17T06:50:55.974517Z]: [configuration][load][end] </usr/local/etc/milter-manager/milter-manager.conf>
[2022-01-17T06:50:55.974641Z]: GLib::Error: <milter-opendkim>: invalid connection spec: milter-connection-error-quark:0: port number has invalid character: <inet:port@localhost>: <p>:
[2022-01-17T06:50:55.974697Z]: (eval):1:in `set_connection_spec'
[2022-01-17T06:50:55.974728Z]: (eval):1:in `connection_spec='
[2022-01-17T06:50:55.974762Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:1189:in `method_missing'
[2022-01-17T06:50:55.974794Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager/detector.rb:44:in `block in apply'
[2022-01-17T06:50:55.974834Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:442:in `define_milter'
[2022-01-17T06:50:55.974870Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager/detector.rb:36:in `apply'
[2022-01-17T06:50:55.974898Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager/freebsd-rc-detector.rb:145:in `apply'
[2022-01-17T06:50:55.974929Z]: /usr/local/etc/milter-manager/defaults/freebsd.conf:57:in `block in load_configuration'
[2022-01-17T06:50:55.974961Z]: /usr/local/etc/milter-manager/defaults/freebsd.conf:54:in `each'
[2022-01-17T06:50:55.974990Z]: /usr/local/etc/milter-manager/defaults/freebsd.conf:54:in `load_configuration'
[2022-01-17T06:50:55.975021Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
[2022-01-17T06:50:55.975050Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
[2022-01-17T06:50:55.975093Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:415:in `block in load'
[2022-01-17T06:50:55.975125Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:414:in `each'
[2022-01-17T06:50:55.975153Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:414:in `load'
[2022-01-17T06:50:55.975185Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:420:in `load_if_exist'
[2022-01-17T06:50:55.975216Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:432:in `load_default'
[2022-01-17T06:50:55.975250Z]: /usr/local/etc/milter-manager/milter-manager.conf:4:in `load_configuration'
[2022-01-17T06:50:55.975280Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `instance_eval'
[2022-01-17T06:50:55.975307Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:383:in `load_configuration'
[2022-01-17T06:50:55.975335Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:344:in `block in load'
[2022-01-17T06:50:55.975373Z]: /usr/local/lib/milter-manager/binding/lib/milter/core/callback.rb:20:in `guard'
[2022-01-17T06:50:55.975403Z]: /usr/local/lib/milter-manager/binding/lib/milter/manager.rb:343:in `load'
[2022-01-17T06:50:55.985744Z]: [configuration][path][nonexistent] path milter-manager.custom.conf doesn't exist in load path (["/usr/local/etc/milter-manager", "/usr/local/etc/milter-manager", "/var/spool/mqueue/.milter-manager"])
[2022-01-17T06:50:55.985894Z]: [manager][process-launcher][pipe] command:<7:8>, reply:<9:10>
[2022-01-17T06:50:55.988762Z]: [1] [reader][watch] <1>:<2>
[2022-01-17T06:50:55.988800Z]: [client][listen][start] <unix:/var/run/milter-manager/milter-manager.sock>
[2022-01-17T06:50:55.988893Z]: [1] [writer][watch] 3
[2022-01-17T06:50:55.989065Z]: [client][socket][unix][group][change] <mail>(<6>): </var/run/milter-manager/milter-manager.sock>
[2022-01-17T06:50:55.989177Z]: [client][socket][unix][mode][change] <0660>: </var/run/milter-manager/milter-manager.sock>
[2022-01-17T06:50:55.989539Z]: [client][group][switch] <mail>(<6>)
[2022-01-17T06:50:55.989627Z]: [client][user][switch] <mailnull>(<26>)
[2022-01-17T06:50:55.989755Z]: [controller][disabled] connection spec isn't specified
[2022-01-17T06:50:55.990898Z]: [client][pid-file][save] </var/run/milter-manager/pid>: <50813>
[2022-01-17T06:50:55.990944Z]: [client][single-thread][single-loop]
[2022-01-17T06:50:55.990965Z]: [cilent][event-loop][glib]
[2022-01-17T06:50:55.991015Z]: [manager][event-loop-created]
[2022-01-17T06:50:55.991042Z]: [configuration][event-loop-created][start]
[2022-01-17T06:50:55.991190Z]: [configuration][event-loop-created][end]
```
確かにクラッシュはしなくなりました。

**Comment by kou** [comment]
`grep '^Socket' /usr/local/etc/mail/opendkim.conf`が`inet:port@localhost`のままになっていますか？

そこを正しい値にしたらエラーがなくなりそうな気がします。

OpenDKIMを無効にしているのにポートを検出しようとしているならmilter managerのバグです。

**Comment by hkuwabara3** [comment]
freebsd.conf　の　 milter-opendkim　はコメントアウトしたらエラーはでなくなりました。

ただ
50888  2  I        0:00.00 /bin/sh /usr/local/etc/rc.d/milter-manager start
50893  2  I        0:00.33 /usr/local/sbin/milter-manager --pid-file /var/run/m
50896  2  I        0:00.00 /usr/local/sbin/milter-manager --pid-file /var/run/m

bg に行かないです。動いてはいるようです。

**Comment by kou** [comment]
それは`ps`の結果ですよね？
`ps -ww`にするとコマンドライン全体が表示されると思うのでコマンドライン全体を見せてもらえますか？

**Comment by hkuwabara3** [comment]
```
50933  2  S+   0:00.00 /bin/sh /usr/local/etc/rc.d/milter-manager start
50941  2  S+   0:00.00 /usr/local/sbin/milter-manager --pid-file /var/run/milter-manager/pid --config-dir=/usr/local/etc/milter-manager --user-name mailnull --group-name mail --unix-socket-group mail --verbose
```

**Comment by kou** [comment]
`rc.conf`で`milter_manager_debug=YES`にしているからですね。
それをコメントアウトすれば最後の`--verbose`が`--daemon`になると思います。

**Comment by hkuwabara3** [comment]
ありがとうございます。クラッシュしたときに追加したままでした。
起動できるようになりました。助かりました。

portsは 2.1.1 なので distinfo だけ 2.1.6にしてビルドしました。

```
distinfo
SHA256 (milter-manager-2.1.6.tar.gz) = 3e656abd3d60677b68a02e35b31d9f7b1d0939fe47dd38425618458b5a5e703f
SIZE (milter-manager-2.1.6.tar.gz) = 6086564
```
その他は、 rubygem-gobject-introspectionを追加しただけでビルドは通るようになりました。

**Comment by kou** [comment]
ではこれは閉じますね。

おいおいportsにもパッチを投げておいてもらえると。。。

たぶん、`rubygem-glib2`への依存を`rubygem-gio2`へ変えることになると思います。`rubygem-gobject-introspection`が`rubygem-gio2`の依存で勝手に入るはずです。

**Comment by hkuwabara3** [comment]
はい、ありがとうございました。
