### ISSUE TITLE
TypeError: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by h3o66** [milter-manager/milter-manager#183]
System: Debian 11

Full Error Message:
```
Dec 11 23:53:04 s1 milter-manager[776940]: TypeError: no implicit conversion of Array into String:
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/core/command-runner.rb:32:in `sync'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/core/command-runner.rb:32:in `run'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/core/command-runner.rb:20:in `run'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/netstat-connection-checker.rb:72:in `netstat'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/netstat-connection-checker.rb:123:in `update_database'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/netstat-connection-checker.rb:105:in `connection_info'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager/netstat-connection-checker.rb:48:in `smtp_server_interface_ip_address'
Dec 11 23:53:04 s1 milter-manager[776940]: /etc/milter-manager/applicable-conditions/sendmail-compatible.conf:14:in `block (2 levels) in load_configuration'
Dec 11 23:53:04 s1 milter-manager[776940]: /etc/milter-manager/applicable-conditions/sendmail-compatible.conf:37:in `block (2 levels) in load_configuration'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:1316:in `block (4 levels) in setup_stoppers'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/core/callback.rb:20:in `guard'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:1315:in `block (3 levels) in setup_stoppers'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:1314:in `any?'
Dec 11 23:53:04 s1 milter-manager[776940]: /usr/lib/x86_64-linux-gnu/milter-manager/binding/lib/milter/manager.rb:1314:in `block (2 levels) in setup_stoppers'

```

This happens diretly after a external client connected to the server.

**Comment by kou** [comment]
Thanks for your report!
I'll release a new version in a few days.

**Comment by h3o66** [comment]
Looks like the link to the issue in the release does not link to this one, instead to another one.

**Comment by kou** [comment]
Good catch!
I've fixed.
