### ISSUE TITLE
Failed to test with rrdtool1.5.4

### ISSUE THREAD

**Issue by okkez** [milter-manager/milter-manager#62]
rrdtool1.5.4でこんなログがいくつか出てテストに失敗する。
milter-manager側で対応が必要っぽい。

```text
Error: test_update(TestLogAnalyzer):
  RuntimeError: failed to run: rrdtool update /home/kenji/wc/milter-manager/test/tool/tmp/session.rrd 1247583600:5:30::: ERROR: /home/kenji/wc/milter-manager/test/tool/tmp/session.rrd: Function update_pdp_prep, 
case DST_GAUGE - Cannot convert '' to float
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:84:in `run'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:32:in `method_missing'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:301:in `flush'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:286:in `feed'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:1154:in `block (2 levels) in update'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:1153:in `each'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:1153:in `block in update'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:1129:in `each_line'
/home/kenji/wc/milter-manager/tool/milter-manager-log-analyzer:1129:in `update'
/home/kenji/wc/milter-manager/test/tool/test-log-analyzer.rb:58:in `test_update'
     55:     milter_status_rrd = (@tmp_dir + "milter.status.milter-greylist.rrd").to_s
     56:     milter_report_rrd = (@tmp_dir + "milter.report.milter-greylist.rrd").to_s
     57: 
  => 58:     @analyzer.update
     59: 
     60:     suffix = "1"
     61:     start_time = Time.parse("2009/07/15 00:00:00")
/home/kenji/wc/milter-manager/test/tool/test-log-analyzer.rb:26:in `run_test'
```

**Comment by okkez** [comment]
#29 と同じかと思ったが、違うっぽい。
